version: "3.9"
services:
  web:
    image: tensorflow/tensorflow:latest-jupyter
    volumes:
      - ./:/tf/notebooks/
    working_dir: /tf/notebooks/local-dev
    ports:
      - 8888:8888
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "source /etc/bash.bashrc && pip install -r requirements.txt && jupyter
          notebook --ip 0.0.0.0 --no-browser --allow-root
          --notebook-dir=/tf/notebooks/local-dev"
      ]
